repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        exclude: tests/
      - id: end-of-file-fixer
        exclude: license_header.txt
      - id: check-yaml
        exclude: .github/repo_meta.yaml
      - id: debug-statements
      - id: check-ast
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.217"
    hooks:
      - id: ruff
        args: [--fix, --exclude, "**/tests/"]
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.990
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
