name: Build

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
    branches:
      - "**"

jobs:
  build:
    name: Build packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            TARGET: macos
            CMD_BUILD: >
              pyinstaller snowcli.spec
            OUT_FILE_DEST: ./dist/snow/
            ARTIFACT_NAME: snow-${{ github.ref_name }}-darwin
          - os: windows-latest
            TARGET: windows
            CMD_BUILD: pyinstaller snowcli.spec
            OUT_FILE_DEST: ./dist/snow/
            ARTIFACT_NAME: snow-${{ github.ref_name }}-windows
          - os: ubuntu-latest
            TARGET: linux
            CMD_BUILD: pyinstaller snowcli.spec
            OUT_FILE_DEST: ./dist/snow/
            ARTIFACT_NAME: snow-${{ github.ref_name }}-linux
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -U pyinstaller
      - name: Build with pyinstaller for ${{matrix.TARGET}}
        run: |
          ${{matrix.CMD_BUILD}}
          cd ./dist/snow
          zip -g ../../snow.zip -r .
      - name: Archive python artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.ARTIFACT_NAME}}
          path: snow.zip
          retention-days: 7
