name: Performance history analysis

on:
  workflow_dispatch:
    inputs:
      rev:
        description: 'Revision (branch, tag, commit hash)'
        required: true
        default: 'HEAD'
      limit_commits:
        description: 'How many commits should be analysed?'
        required: true
        default: '50'
      sample_amount:
        description: 'How many runs of SnowCLI should be performed for each commit?'
        required: true
        default: '20'

permissions:
  contents: read

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: ${{ github.event.inputs.limit_commits }}
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Run performance history analysis
        run:
          python performance_history_analysis.py --print-all-results --rev ${{ github.event.inputs.rev }} --limit-commits ${{ github.event.inputs.limit_commits }} --sample-amount ${{ github.event.inputs.sample_amount }}
